### ISSUE TITLE
Add "Simple Snippet - Icon with Text" Activity Stream Snippet Template 

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets#116]
![screen shot 2017-07-13 at 2 05 34 pm](https://user-images.githubusercontent.com/6807556/28187692-71579bda-67d4-11e7-954b-900977f9f082.png)

https://mozilla.invisionapp.com/share/YD7X9Z7GX#/screens/187604366_New_Tab-Snippets

**Comment by glogiotatidis** [comment]
Fixed in https://github.com/mozmeao/snippets/commit/9efb706ec960f2c0503af3958dc6f773a822cbea
