### ISSUE TITLE
Add "Simple Snippet - Icon, text and call to action" Activity Stream Snippet

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets#117]
![screen shot 2017-07-13 at 2 19 05 pm](https://user-images.githubusercontent.com/6807556/28188222-47bba24c-67d6-11e7-9264-cc073c120656.png)

https://mozilla.invisionapp.com/share/YD7X9Z7GX#/screens/187604366_New_Tab-Snippets

**Comment by glogiotatidis** [comment]
Fixed in https://github.com/mozmeao/snippets/commit/9efb706ec960f2c0503af3958dc6f773a822cbea

**Comment by jkt230** [comment]
Reopening this issue as there are slight updates needed to this template. Here are the new specs:
https://mozilla.invisionapp.com/share/D4D6BPMGH#/screens/249240594_New_Tab_-_Onboarding_Measurements

It's under onboarding but the specs are the same for onboarding snippets and regular snippets.

**Comment by jkt230** [comment]
Tagging @scottdowne

**Comment by glogiotatidis** [comment]
@ScottDowne is this something you could take on?

**Comment by ScottDowne** [comment]
Yup I had it pretty much done Friday. Just wanted to go over it once today
and then make a pull request.

**Comment by ScottDowne** [comment]
There were changes in both the snippet css and the enippet-service css, pull requests are:

https://github.com/mozmeao/snippets/pull/124
https://github.com/mozmeao/snippets-service/pull/280

They only really make sense when used together.

**Comment by glogiotatidis** [comment]
Pushed to production
