### ISSUE TITLE
Add "Fundraising snippet" Activity Stream Snippet Template

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets#118]
![screen shot 2017-07-13 at 2 19 56 pm](https://user-images.githubusercontent.com/6807556/28188303-8b3ae212-67d6-11e7-907d-a076afeb6a86.png)

https://mozilla.invisionapp.com/share/YD7X9Z7GX#/screens/187604366_New_Tab-Snippets

**Comment by glogiotatidis** [comment]
https://github.com/mozmeao/snippets/blob/master/activity-stream/mofo-eoy-2017.html
