### ISSUE TITLE
Add "Video Snippet" Activity Stream Snippet Template

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets#119]
![screen shot 2017-07-13 at 2 20 03 pm](https://user-images.githubusercontent.com/6807556/28188330-9de46956-67d6-11e7-8648-19b170153ffe.png)

https://mozilla.invisionapp.com/share/YD7X9Z7GX#/screens/187604366_New_Tab-Snippets

**Comment by glogiotatidis** [comment]
https://github.com/mozmeao/snippets/pull/134

**Comment by glogiotatidis** [comment]
https://github.com/mozmeao/snippets/pull/134
