### ISSUE TITLE
Close button should only appear on hover

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets#121]
In activity stream the close snippet button should appear only on hover and be normally hidden according to the mockups.

**Comment by glogiotatidis** [comment]
@ScottDowne would you like to fix this when you have some time?

**Comment by ScottDowne** [comment]
This should do it: https://github.com/mozmeao/snippets/pull/122

**Comment by ScottDowne** [comment]
@glogiotatidis I think we can close this.
