### ISSUE TITLE
Activity Stream button snippet opt out UI issue

### ISSUE THREAD

**Issue by ScottDowne** [mozmeao/snippets#123]
I noticed this yesterday testing something else:

![x-button](https://user-images.githubusercontent.com/197334/28977663-f6503de0-7910-11e7-8aa1-df255609798f.png)

If you view the snippet with a button at half screen size, the x button gets awfully close to the snippet button.

If the snippet button has a bit more text, it could even overlap the buttons, which is probably bad if people opt out when they wanted to opt in.

I have a solution in mind, but I wanted to run it by Aaron when he gets back.

@glogiotatidis Thoughts?

**Comment by jkt230** [comment]
@ScottDowne Giorgos is out on PTO - feel free to run by Aaron!

**Comment by ScottDowne** [comment]
I had a chat with Aaron about this, but I'm not sure where he ended up decision wise. (we talked on slack)

I guess it doesn't help much that he hasn't been pinged in this issue ;) Is he on github though?

**Comment by glogiotatidis** [comment]
@ScottDowne would be so kind to remind me whether we fixed this or not? If not is this still an issue?

**Comment by ScottDowne** [comment]
Yeah a solution ended up landing with another fix.

**Comment by glogiotatidis** [comment]
Thanks!
