### ISSUE TITLE
Activity stream snippets rtl

### ISSUE THREAD

**Issue by ScottDowne** [mozmeao/snippets#125]
@glogiotatidis I noticed the about:home page for activity stream is setting dir="ltr"

Which means, if it also sets dir="rtl" in appropriate locales, we can probably remove a handful of css in our snippet.

**Comment by glogiotatidis** [comment]
Good point @ScottDowne. Your good friend @k88hudson took take of that in #126. I just tested with Arabic firefox and it works like a charm. Thanks both!
