### ISSUE TITLE
Need locale input field in: Newsletter Template for Activity Stream 

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets#135]
Hi @jpetto noticed that we can't input locale which we need to make sure the right newsletter is being sent.

**Comment by jpetto** [comment]
Hm, I must have misunderstood something in the requirements. I thought the locale(s) that should display the snippet were chosen in the "Country and Locale" section of the admin.

Do we need a locale value used within the snippet itself? If so, where should it be applied? Does it need to be sent along to basket?

**Comment by glogiotatidis** [comment]
> Hm, I must have misunderstood something in the requirements. I thought the locale(s) that should display the snippet were chosen in the "Country and Locale" section of the admin.

Correct. We control the display of the snippets based on locale. What we also want to subscribe users to a newsletter based on locale. 

> Do we need a locale value used within the snippet itself? If so, where should it be applied? Does it need to be sent along to basket?

Yes basket needs to know the locale. To fix this:

1. Create a new variable locale, default to "en-US",  snippet editors will change if needed 
2. Sent it to basket

Here's the old newsletter signup snippet that works with locale.
 - https://github.com/mozmeao/snippets/blob/master/generic-templates/newsletter-signup-snippet/

**Comment by glogiotatidis** [comment]
And since you already have the locale variable there you only need to send it to basket as `lang` for both sms and emails

**Comment by jpetto** [comment]
🤦‍♂️ Sigh, of course. My brain has been in bedrock too long, where the locale is grabbed from the URL and automatically sent to basket in the view. Will issue a PR shortly.
