### ISSUE TITLE
Need to fix the phone number logic for Send to Device Template for Activity Stream

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets#136]
Hi @jpetto,

We're testing out the Send to Device template and noticed that sending in a number like 4253510028, it doesn't send a text. I think we need to automatically add the country code 1. However, when I try to enter 14253510028, the template doesn't let me hit the button (not clickable). 

I believe in the old template the 1 was automatically populated. Can we do that for this template?

**Comment by jpetto** [comment]
Odd. In development, I was entering my phone number without country code and was receiving texts. Can you point me to the URL you're testing against so I can try to replicate?

**Comment by jkt230** [comment]
@glogiotatidis I think the phone logic is working but what I've noticed is that in preview for both the Send to Device and the Newsletter templates for Activity Stream - it uses the old logo background and not the Activity Stream background. 

Example: Snippet ID 7711 or  https://snippets-admin.us-west.moz.works/show/uuid/6a274140-d33d-42cb-8dd9-ca4ed244f717/

If we can get it fixed so it's the AS preview, I'll be able to take a look and test it further and will close this issue out if there are no more problems.

**Comment by glogiotatidis** [comment]
@jkt230 you forgot to select 'activity stream' in the start page versions and that's why you got the old template. I changed it for you

Do you want to default to AS instead of versions '2,3,4' from now on?

**Comment by jkt230** [comment]
Hah thanks for calling that out @glogiotatidis 

Yes please, can we default to AS from now on?

**Comment by glogiotatidis** [comment]
> Yes please, can we default to AS from now on?

tracked in https://github.com/mozmeao/snippets-service/issues/341
