### ISSUE TITLE
Activity Stream Snippets Metrics

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets#139]
@glogiotatidis 
1) Can you confirm that in Tableau and GA, click gets recorded when you hit a button in the first scene of a snippet like Snippet 7725 or https://snippets-admin.us-west.moz.works/show/uuid/80c14e0a-e1d2-465e-8d32-d03d4deb84b6/ - I know 'click' gets recorded when you hit a hyperlink in the copy of the snippet but I wanted to double confirm for the button

2) Can we start measuring the "Nevermind" button clicks in the second scene of a snippet like Snippet 7725 or https://snippets-admin.us-west.moz.works/show/uuid/80c14e0a-e1d2-465e-8d32-d03d4deb84b6/

**Comment by glogiotatidis** [comment]
> Can you confirm that in Tableau and GA, click gets recorded when you hit a button in the first scene of a snippet like Snippet 7725 or https://snippets-admin.us-west.moz.works/show/uuid/80c14e0a-e1d2-465e-8d32-d03d4deb84b6/ - I know 'click' gets recorded when you hit a hyperlink in the copy of the snippet but I wanted to double confirm for the button

No those are not recorded since they are not hyperlinks. Do you want those recorded with the metric `click` or a different one?

@jpetto can you update your templates with `sendMetric('whatever-jean-chooses')` in the functions that handle move from `scene1` to `scene2`?

**Comment by glogiotatidis** [comment]
> Can we start measuring the "Nevermind" button clicks in the second scene of a snippet like Snippet 7725 or https://snippets-admin.us-west.moz.works/show/uuid/80c14e0a-e1d2-465e-8d32-d03d4deb84b6/

This we're already collecting as `snippet-blocked` and actually blocks the snippet. Is this the wanted behavior?

**Comment by jpetto** [comment]
> @jpetto can you update your templates with sendMetric('whatever-jean-chooses') in the functions that handle move from scene1 to scene2?

Yep, should be easy enough to add `sendMetric` calls when switching scenes. I'll just need the values for each template.

**Comment by jkt230** [comment]
@jpetto please see: https://github.com/mozmeao/snippets/issues/140

**Comment by glogiotatidis** [comment]
Replaced by #140
