### ISSUE TITLE
Define metrics for Activity Stream templates

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets#140]
We currently have four generic Activity stream templates:

 1. Simple Snippet
 2. Send To Device
 3. Simple Video Snippet
 4. Newsletter Subscribe
 5. FxA Subscribe

### Simple Snippet
- [X] X Button to block snippet [name: `snippet-blocked`]
- [X] Hyperlink Clicked [name: `click`]
- [x] Button Clicked [name: `button-click`]

### Send to Device
 - [X] X Button to block snippet [name: `snippet-blocked`]
 - [x] Learn More Button (Scene 1) [name: `button-click`]
 - [x] Send Button (Scene 2)
   - When email [name: `conversion-mobile-activation-email`] 
   - When sms [name: `conversion-mobile-activation-sms`]
 - [x] Nevermind Button (Scene 2) - works as X block button - [name: snippet-scene2-blocked]
 - [x] `activation-email-success` - basket success sending email
 - [x] `activation-email-error` - basket success sending email
 - [x] `activation-SMS-success` - basket success sending SMS
 - [x] `activation-SMS-error` - basket error sending SMS

### Simple Video Snippet
 - [X] X Button to block snippet [name: `snippet-blocked`]
 - [x] Watch Button (Scene 1) [name: `button-click`]
 - [x] Video Complete [name: `conversion-video-complete`]
 - [x] Done Button (Scene 2) [name: `video-done`]

### Newsletter Subscribe
 - [X] X Button to block snippet [name: `snippet-blocked`]
 - [x] Learn More Button (Scene 1) [name: `button-click`]
 - [x] Nevermind Button (Scene 2) - works as X block button - [name: `snippet-scene2-blocked`]
 - [x] Sign Me Up button [name: `conversion-subscribe-activation`]
 - [x] Subscribe success [name: `subscribe-success`]
 - [x] Subscribe error [name: `subscribe-error`]

### FxA Subscribe
 - [x] X Button to block snippet [name: `snippet-blocked`]
 - [x] Learn More Button (Scene 1) [name: `button-click`]
 - [x] Nevermind Button (Scene 2) - works as X block button - [name: `snippet-scene2-blocked`]
 - [x] Sign Me Up button [name: `conversion-subscribe-activation`]

**Comment by glogiotatidis** [comment]
@jkt230 This issue lists the currently collected metrics (checked) and additional potential metrics for each.

Please review and select which one of the additional metrics you want. For each new metric you'll have to provide a metric name, like `video-watched`, `subscribe-success`.

/cc @jpetto

**Comment by jkt230** [comment]
Thanks Giorgos. One thing to add is that the simple snippet also has a button (which we use if we don't do the hyperlink). I'm going to try and copy and paste above and add the metric name:

Simple Snippet

    X Button to block snippet [name: snippet-blocked]
    X Hyperlink Clicked [name: click]
       Button Clicked [name: button-click]

Send to Device

    X Button to block snippet [name: snippet-blocked]
    X Learn More Button (Scene 1) [name: button-click]
    X Send Button (Scene 2) [I think this was labelled: conversion-mobile-activation-email AND conversion-mobile-activation-sms]
        Do we want to track differently sent emails and sent smses? Yes, please see above
        If so maybe a common for both as well? [name: conversion-mobile-activation] open to suggestions on this one.
    Nevermind Button (Scene 2) - works as X block button, can we label this one as [name: snippet-scene2-blocked], want to track these blocks separately from the "snippet-blocked" 

Simple Video Snippet

    X Button to block snippet [name: snippet-blocked]
    Watch Button (Scene 1) [name: button-click]
    Video Play? [name: conversion-video-play]
    Video Complete? [name: conversion-video-complete]
    Done Button (Scene 2) [name: video-done]

Newsletter Subscribe

    X Button to block snippet  [name: snippet-blocked]
    Learn More Button (Scene 1) [name: button-click]
    Nevermind Button (Scene 2) - works as X block button [name: snippet-scene2-blocked]
    Sign Me Up button? [name: conversion-email-activation]
    Subscribe success? [name: success-message]
    Subscribe error? [name: error-message]

**Comment by jkt230** [comment]
@glogiotatidis @jpetto

**Comment by glogiotatidis** [comment]
> @glogiotatidis @jpetto

@jkt230 fyi you don't have to mention us every time. If mentioned once, then you get all emails for the issue.

**Comment by glogiotatidis** [comment]
For the "Never mind" button clicks we can use `data-metric="snippet-scene2-blocked"` in the button, the same way. I just pushed https://github.com/mozmeao/snippets-service/pull/351 to enable this.

All the other events can call `sendMetric()`

@jpetto is this something you can take care? If so while you're at it maybe you can also tackle https://bugzilla.mozilla.org/show_bug.cgi?id=1436516

**Comment by jpetto** [comment]
Jean - Is there a metric you want to send on the FxA snippet when the user clicks the form submit button?

**Comment by jkt230** [comment]
Giorgos thanks for letting me know about the mention :) 

Jon, let's do "conversion-subscribe-activation" - thanks!

**Comment by jpetto** [comment]
Giorgos - Do we need to delay the default action in order for `sendMetric` to have time to execute, or can the event handler call `sendMetric` and then immediately perform the default action?

In other words, 

```
// immediately call default action
link.addEventListener('click', e => {
    e.preventDefault();
    sendMetric('clicked');
    window.location.href = link.href;
});
```

or

```
// delay default action by 300ms
link.addEventListener('click', e => {
    e.preventDefault();
    sendMetric('clicked');
    setTimeout(() => {
        window.location.href = link.href;
    }, 300);
});
```

**Comment by glogiotatidis** [comment]
> Giorgos - Do we need to delay the default action in order for sendMetric to have time to execute, or can the event handler call sendMetric and then immediately perform the default action?

good question. `sendMetric` accepts a callback which you can use for this.

https://github.com/mozmeao/snippets-service/blob/master/snippets/base/templates/base/includes/snippet_as.js#L454

**Comment by jpetto** [comment]
Jean - Do you want to track successes and errors on the send to device snippet? (You've requested subscribe success/error tracking for the newsletter snippet above - we could do similar for send to device.)

**Comment by jkt230** [comment]
That would be great, thanks Jon! Should we do it separately for each conversion? 
Such as:
activation-email-success
activation-email-error
activation-SMS-success
activation-SMS-error

**Comment by glogiotatidis** [comment]
This is now in prod. Thanks!
